### ISSUE TITLE
[CS:GO ZE] Leader is not a zombie

### ISSUE THREAD

**Issue by BABEP** [net4allru/n4a-public#3]
Сделать что бы лидер с шансом 100% не становился первым зомби.

**Comment by razstiker** [comment]
Тогда будут абузить лидерку.
Если уж выпала судьба стать зомби, то так и будет.

**Comment by net4allru** [comment]
Согласен с @razstiker , но думаю тут нужен немного другой функционал, а именно:
Возможность админу поставить иммунитет от заражения, чтобы во время "ивента" и наличии "командующего", мы могли поставить ему иммунитет и он мог спокойно лидить. Что скажете @razstiker @BABEP ?

**Comment by razstiker** [comment]
В общем пока что останется, как есть.
